### ISSUE TITLE
consider detaching this fork from upstream

### ISSUE THREAD

**Issue by dwijnand** [rust-lang-nursery/highfive#131]
there are downsides to having a live fork also be a fork within GitHub because, for instance, it affects your ability to use GitHub search on the code:

https://github.com/rust-lang-nursery/highfive/search?q=reviewer&type=Code

however, it's possible to request that the repo be made a standalone repository:

> To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub Support](https://github.com/contact). If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "[About forks](https://help.github.com/articles/about-forks/)."

(from https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork)

I was able to follow this process to detach a fork with the following message:

> Hi GitHub Support!
> 
> As detailed in https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork, please could you detach https://github.com/sbt/sbt-launcher-package from https://github.com/paulp/sbt-extras, turning it into a standalone repository. Note I co-maintain both, but they're distinct entities at this point.
> 
> Also, any fork of sbt/sbt-launcher-package should move with sbt/sbt-launcher-package into a new network, rather than remain in the current network.
> 
> Thank you,
> Dale

**Comment by nrc** [comment]
Interesting, I did not realise that was possible. I have contacted GitHub support, so hopefully this can happen soon.

**Comment by dwijnand** [comment]
cool, thanks @nrc

**Comment by dwijnand** [comment]
done:

![image](https://user-images.githubusercontent.com/344610/38607138-c7739bc4-3d6f-11e8-8d60-6d6c274aafea.png)
