### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by davidalber** [rust-lang-nursery/highfive#141]
rust-lang-nursery/highfive does not have a license. [servo/highfive does: MPL](https://github.com/servo/highfive/blob/master/LICENSE), which was added a couple years after rust-lang-nursery/highfive forked from servo/highfive. Rust projects [seem to like licensing with Apache v2 and MIT](https://www.rust-lang.org/legal.html).

**Comment by nrc** [comment]
Good idea. I'd prefer Apache 2/MIT for easier interaction with the rest of the Rust ecosystem

**Comment by davidalber** [comment]
Sounds good. Under more general circumstances I would say I don't think we have the right to do that given the licensing of the content that came over from servo/highfive. At least not without their permission. Since there was no license when the fork was made it's unclear what the terms of the forked code were at the time.

However, I said "general circumstances" above because this may be completely academic given the association between Servo and Mozilla and the initial developer and Mozilla. Is that your take (i.e., everything I'm talking about is Mozilla), @nrc, and if yes, you feel that we can just drop the Apache 2 and MIT licenses in without asking Mozilla Legal (or whoever) and move on?
