### ISSUE TITLE
Still prefer adding commits over amending and force-pushing?

### ISSUE THREAD

**Issue by dwijnand** [rust-lang-nursery/highfive#188]
The new PR welcome message says:

> If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

With GitHub introducing [Force push timeline event](https://blog.github.com/changelog/2018-11-15-force-push-timeline-event/) are extra commits still preferred over amended and force-pushed commits?

**Comment by Mark-Simulacrum** [comment]
Yes, in general, because GitHub still doesn't notify for force pushed commits.
